server:
  iPVersion: "tcp4"
  name: "fire"
  host: "0.0.0.0"
  tcpPort: 30119
#  tcpPort: 4660
  httpPort: 20119
  maxConn: 3
  workerPoolSize: 10
edgeserver:
  name: "edgeplanet"
  host: "192.168.233.32"
  port: 30090
mqtt:
  qos: 1
  retain: false
  server: "tcp://192.168.199.12:1883"
  username: "root"
  password: "root"
  certification:
#configmap: "/opt/kubeedge/deviceProfile.json"
configmap: "config/deviceProfile.json"
domancode:
  code:
    # 1m3
    "msantwo": "1.1"
    "edge-bacnet-2"  : "2.1"










